name: fjsp-system
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy>=1.21.0
  - pandas>=1.3.0
  - matplotlib>=3.5.0
  - scipy>=1.7.0
  - networkx>=2.6.0
  - pyyaml>=6.0.0
  - requests>=2.26.0
  - plotly>=5.0.0
  - flask>=2.0.0
  - tqdm>=4.62.0
